"""Ajout champs date_created et date_updated dans Client

Revision ID: 10dc317dc2ac
Revises: b069ba08e7ef
Create Date: 2024-04-03 11:17:14.621708

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '10dc317dc2ac'
down_revision = 'b069ba08e7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('date_updated')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
