"""Update client table

Revision ID: 486f04b28083
Revises: ff2d57a829e8
Create Date: 2024-04-04 15:52:07.828435

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '486f04b28083'
down_revision = 'ff2d57a829e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hostname', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('hostname')
        batch_op.drop_column('os_version')
        batch_op.drop_column('os')

    # ### end Alembic commands ###
