"""Ajout champ sid dans Client

Revision ID: b069ba08e7ef
Revises: 399b84aafbf0
Create Date: 2024-04-03 11:03:15.504170

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b069ba08e7ef'
down_revision = '399b84aafbf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('sid')

    # ### end Alembic commands ###
